# Generated by Django 2.2.3 on 2019-07-07 19:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=48)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=20)),
                ('last_name', models.CharField(blank=True, default='', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=11)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=11)),
                ('age', models.CharField(blank=True, default='', max_length=3)),
                ('group', models.CharField(blank=True, default='patients', max_length=30)),
                ('nation_code', models.CharField(blank=True, default='1234567890', max_length=10)),
                ('height', models.CharField(blank=True, default='', max_length=3)),
                ('weigth', models.CharField(blank=True, default='', max_length=3)),
                ('address', models.CharField(blank=True, default='', max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('gender', models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.')], default='MR', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angina', models.BooleanField()),
                ('history_of_mi', models.BooleanField()),
                ('prior_cath', models.BooleanField()),
                ('prior_cabg', models.BooleanField()),
                ('smoking', models.BooleanField()),
                ('diabetic', models.BooleanField()),
                ('family_history', models.BooleanField()),
                ('paec_maker', models.BooleanField()),
                ('indications', models.CharField(blank=True, default='', max_length=120)),
                ('medications', models.CharField(blank=True, default='', max_length=120)),
                ('procedure_type', models.CharField(choices=[('24:00 H', '48:00 H'), ('48:00 H', '48:00 H')], default='MR', max_length=3)),
                ('referring_physician', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.CharField(blank=True, default='', max_length=250)),
                ('technicain_name', models.CharField(blank=True, default='', max_length=30)),
                ('attending_phy', models.CharField(blank=True, default='', max_length=30)),
                ('request_time_data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.CharField(blank=True, default='', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
