# Generated by Django 2.2.3 on 2019-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='procedure_type',
            field=models.CharField(choices=[('24:00 H', '48:00 H'), ('48:00 H', '48:00 H')], default='MR', max_length=10),
        ),
    ]
