# Generated by Django 2.2.3 on 2020-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0003_auto_20200131_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='procedure_type',
            field=models.CharField(choices=[('24:00 H', '24:00 H'), ('48:00 H', '48:00 H')], default='MR', max_length=10),
        ),
    ]
